### ISSUE TITLE
Contributors wanted?

### ISSUE THREAD

**Issue by actuallymentor** [ethereum/mist-ui#8]
Hello!

Is this project looking for contributions in any specific area? I can't spot a contribution guide in this repo.

**Comment by PhilippLgh** [comment]
Absolutely! A guideline will be added later today. Are you interested in contributing and if so what are your areas of interest?
The main part of work right now is centered around integrating various Ethereum clients starting with geth (NodeConfig, NodeSetup) and integrating and styling components from (https://github.com/ethereum/ethereum-react-components)[https://github.com/ethereum/ethereum-react-components]. The browser related pieces are not part of our MVP roadmap for the re-write.

**Comment by actuallymentor** [comment]
My skills are in the React/Node area, anything in there I'm happy to help with. I did the initial Dutch translation of Mist way back when but didn't contribute since then.

**Comment by marcgarreau** [comment]
@actuallymentor thanks for asking! We'd love the help, but need to spend some time creating and labeling issues. This is one of my goals is the near future, but in the meantime you could familiarize yourself with the codebase by checking/updating things like `PropTypes` and other low-hanging fruit. While doing a mass-linting, I just set many of them to accept `any` value. Perhaps other refactors will stand out while doing that. Just an idea. I will also add some documentation around contribution today.

**Comment by actuallymentor** [comment]
Looking forward to the docs. I'm happy to take some low hanging fruit :)

**Comment by marcgarreau** [comment]
Here's a [first pass](https://github.com/ethereum/mist-ui/blob/master/docs/CONTRIBUTING.md) at some guidelines @actuallymentor. I'm going to close this issue, but if you have follow-up questions, feel free to continue posting here.
